---
title: "ESA Species Mapping"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    css: custom.css
    social: menu
    df_print: paged
    navbar:
      - {title: "CCI", align: left, href: "https://cci-dev.org", target: "_blank"}
      - {title: "Defenders", align: left, href: "http://www.defenders.org"}
      - {title: "", icon: "fa-envelope-o fa-lg", align: right, href: "mailto:esa@defenders.org?subject=species mapper"}
      - {title: "", icon: "fa-github fa-lg", align: right, href: "https://github.com/jacob-ogre/ESA_species_maps"}
runtime: shiny
---

```{r setup, include=FALSE}

library(bsplus)
library(DBI)
library(dplyr)
library(ecosscraper)
library(leaflet)
library(rio)
library(RSQLite)
library(shiny)
library(shinyBS)
library(shinydashboard)

# use_bs_tooltip()

# db connection
con <- dbConnect(RSQLite::SQLite(), "data/ESA_GBIF.sqlite3")

# This uses the TECP table from when I pulled data from GBIF...it may be out-
# of-date at the time this app is run, but that's fine because we don't make
# real-time GBIF API calls for specimen data, so would be missing such data for
# for newly listed species anyway...
TECP_table <- readRDS("data/TECP_table.rds")

# A df for name cross-referencing between ECOS names and GBIF
spp_xref <- readRDS("data/gbif_keys_xref.rds")

# A df linking five-year reviews to species names for reference
fiveyr_table <- readRDS("data/five_year_table.rds")
recovery_table <- readRDS("data/recovery_table.rds")

```

```{r functions, echo=FALSE}
```

Inputs {.sidebar}
-----------------------------------------------------------------------

```{r selector, echo = FALSE}
species <- sort(unique(TECP_table$names))
wellPanel(
  tags$b("Data inputs"),
  hr(),
  selectInput(
    "sel_species",
    label = "Species",
    choices = species,
    selected = "Kirtland's Warbler (Setophaga kirtlandii (= Dendroica kirtlandii))"
  ),
  
  checkboxGroupInput(
    "select_opts",
    "Layers",
    choiceNames = 
      list("placenames", "GBIF", "counties"),
    choiceValues = 
      list("place", "gbif", "counties"),
    selected = c("place", "gbif")
  ),

  checkboxGroupInput(
    "select_details",
    "Details",
    choiceNames = 
      list("Incl. populated places?"),
    choiceValues = 
      list("pop_place"),
    selected = c("pop_place")
  ),
  bsTooltip(
    id = "select_details", 
    title = "Populated places tend to have more false-positives"
  )
)

wellPanel(
  tags$b("Reference docs"),
  hr(),
  htmlOutput("fiveyr_url"),
  htmlOutput("recovery_url")
)

wellPanel(
  tags$b("Download Data"),
  hr(),
  fluidRow(
    column(6,
      downloadButton(
        "download_gbif",
        "GBIF"
      )
    ),
    column(6,
      downloadButton(
        "download_geonames",
        "Places"
      )
    )
  )
)
```
  
```{r downloads, echo=FALSE}
output$download_gbif <- downloadHandler(
  filename=function() {
    paste0(
      gsub(cur_xref()$name, pattern = " ", replacement = "_"),
      "_gbif.xlsx"
    )
  },
  content=function(file) {
    export(cur_gbif(), file=file)
  }
)

output$download_geonames <- downloadHandler(
  filename=function() {
    paste0(
      gsub(cur_xref()$name, pattern = " ", replacement = "_"),
      "_places.xlsx"
    )
  },
  content=function(file) {
    export(cur_plc(), file=file)
  }
)
```

```{r proc_gbif_place, echo=FALSE}
cur_ecos <- reactive(
  if(!is.null(input$sel_species)) {
    filter(TECP_table, names == input$sel_species)
  } else {
    NULL
  }
)

cur_xref <- reactive(
  if(!is.null(cur_ecos())) {
    filter(spp_xref, search == cur_ecos()$species)
  } else {
    NULL
  }
)

cur_gbif_q <- reactive(
  if(!is.null(cur_ecos())) {
    sprintf("SELECT * FROM esa_gbif WHERE taxon_key = '%s'", cur_xref()$key)
  } else {
    NULL
  }
)

cur_plc_q <- reactive(
  if(!is.null(cur_ecos())) {
    sprintf(
      "SELECT * FROM fiveyr_place WHERE species = '%s'", 
      cur_ecos()$species
    )
  } else {
    NULL
  }
)

cur_gbif <- reactive(
  if(!is.null(cur_gbif_q())) {
    dbSendQuery(con, cur_gbif_q()) %>% 
      dbFetch() %>%
      filter(!is.na(dec_latitude) & dec_latitude != 0.0)
  } else {
    NULL    
  }
)

cur_plc <- reactive(
  if(!is.null(cur_plc_q())) {
    q1 <- dbSendQuery(con, cur_plc_q()) %>% 
      dbFetch() %>%
      filter(prim_lat_dec != 0.0)
    if(!("pop_place" %in% input$select_details)) {
      q1 <- filter(q1, feature_class != "Populated Place" &
                     feature_class != "Civil")
    }
    q1
  } else {
    NULL    
  }
)


```

```{r docs_proc, echo=FALSE}
output$fiveyr_url <- reactive({
  href <- filter(fiveyr_table, Species == cur_ecos()$species)$Doc_Link 
  paste0(tags$a("Five-year Review", href = href, target = "_blank"))
})

output$recovery_url <- reactive({
  href <- filter(recovery_table, Species == cur_ecos()$species)$Doc_Link 
  paste0(tags$a("Recovery Plan", href = href, target = "_blank"))
})
```

Row {data-height=1000}
-----------------------------------------------------------------------

### 
```{r map, echo=FALSE}
renderLeaflet({
  map1 <- leaflet(data = cur_gbif()) %>%
    addProviderTiles(provider = input$sel_basemap) 
  
  if("place" %in% input$select_opts) {
    map1 <- map1 %>%
      addCircleMarkers(
        lng = cur_plc()$prim_long_dec,
        lat = cur_plc()$prim_lat_dec,
        radius = 5,
        weight = 1,
        opacity = 0.3,
        color = "red",
        popup = ~paste0(
          "<b>Term: ", cur_plc()$terms, "</b><br>",
          "<smaller><b>Feature class:</b> ", 
          cur_plc()$feature_class, "</smaller>",
          "<br><b>Long & Lat:</b><br>",
          cur_plc()$prim_long_dec, ", ",
          cur_plc()$prim_lat_dec)
      )
  }
  
  if("gbif" %in% input$select_opts) {
    map1 <- map1 %>%
      addMarkers(
        lng = cur_gbif()$dec_longitude,
        lat = cur_gbif()$dec_latitude,
        popup = ~paste0(
          "<b>Date: ", as.Date(cur_gbif()$date, origin = "1900-01-01"),
          "</b><br>",
          "<smaller><b>Locality:</b> ", cur_gbif()$locality, "</smaller>",
          "<br><b>Long & Lat:</b><br>",
          cur_gbif()$dec_longitude, ", ",
          cur_gbif()$dec_latitude,
          "<br><b style='color:red'>Coord. issue: ",
          issues, "</b><br>")
      )
  }
  
  map1
})
```

```{r map_ctrl, echo=FALSE}
absolutePanel(
  id = "mapcontrols",
  class = "float_panel",
  top = "100px",
  right = "50px",
  left = "auto",
  bottom = "auto",
  fixed = TRUE,
  draggable = FALSE,
  
  selectInput(
    "sel_basemap",
    label = "Basemap",
    width = "125px",
    choices = list(
      "Terrain" = "Stamen.Terrain",
      "Basic" = "Stamen.TonerLite",
      "Imagery" = "Esri.WorldImagery"
    ),
    selected = "StamenTerrain")
  
)
```

